### ISSUE TITLE
Add submenu to SGGS MenuItem

### ISSUE THREAD

**Issue by bogas04** [bogas04/SikhJS#42]
Submenu should have items like
- [ ] Sehaj Paath (#20)
- [x] Bookmarks (#20)
- [x]  Authors (#38)  
- [x] Raags 
  - [x] `/raags` with list of all raags
  - [x] `/raags/:id` with description of raag, and link to start ang of sggs.

**Comment by bogas04** [comment]
Raag Angs can use following CSS to be closer to an actual Saroop.

``` js
raagAngs = [1, ...];
let className = ['gurbani-text', 'gurbani-text raag-ang'][raagAngs.includes(ang) ? 1 : 0]
...
<div style={{ textAlign: 'left', padding: 20 }} className={className}>{angContent}</div>
```

``` css
.gurbani-text.raag-ang > div:nth-child(1) {
  font-size: 2em !important;
  display: block !important;
  text-align: center !important;
}
.gurbani-text.raag-ang > div:nth-child(2) {
  display: block !important;
  text-align: center !important;
  font-size: 1.25em !important;
}
.gurbani-text.raag-ang {
  background-color: #452f5a; /* Can be random as well */
  color: white;
}
```
